name: reactor
description: JoyReactor client.
version: 0.6.0

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  video_player: # null_safety
    git:
      url: https://github.com/AlimZanibekov/plugins.git
      ref: videoplayer_headers_cache
      path: packages/video_player/video_player
  dio: ^4.0.0 # null_safety
  html: ^0.15.0 # null_safety
  page_transition: ^2.0.2 # null_safety
  flutter_inappwebview: ^5.3.2 # null_safety
  url_launcher: ^6.0.4 # null_safety
  decorated_icon: ^1.2.0 # null_safety
  shared_preferences: ^2.0.5 # null_safety
  advanced_image: # null_safety
    path: /Users/alimzanibekov/AndroidStudioProjects/advanced_image
  #  ext_storage: ^1.0.3
  permission_handler: ^8.0.0+1 # null_safety
  double_back_to_close_app: ^2.0.1 # null_safety
  scrollable_positioned_list: ^0.2.0-nullsafety.0 # null_safety
  uni_links: ^0.5.1 # null_safety
  sentry: ^5.0.0 # null_safety
  file_picker: ^3.0.1 # null_safety
  device_info: ^2.0.1 # null_safety
  package_info: 2.0.0 # null_safety
  #  flutter_user_agent: ^1.2.2
  path_provider: ^2.0.1 # null_safety
  flutter_local_notifications: ^6.0.0 # null_safety
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.15.7
  flutter_test:
    sdk: flutter


flutter:
  assets:
    - assets/icons/
  uses-material-design: true
