name: reactor
description: JoyReactor client.
version: 0.8.2

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  video_player:
    git:
      url: https://github.com/alim-zanibekov/plugins.git
      ref: videoplayer_headers_cache
      path: packages/video_player/video_player
  advanced_image:
    git:
      url: https://github.com/alim-zanibekov/advanced_image.git
      ref: master
  dio: ^4.0.4
  html: ^0.15.1
  page_transition: ^2.0.9
  flutter_inappwebview: ^5.7.1
  url_launcher: ^6.1.6
  decorated_icon: ^1.2.1
  shared_preferences: ^2.0.15
  permission_handler: ^10.2.0
  double_back_to_close_app: ^2.1.0
  scrollable_positioned_list: ^0.3.5
  uni_links: ^0.5.1
  sentry: ^6.14.0
  file_picker: ^5.2.2
  device_info_plus: ^8.0.0
  package_info_plus: ^3.0.1
  path_provider: ^2.0.11
  flutter_local_notifications: ^12.0.3
  share_plus: ^6.2.0
  mime: ^1.0.2

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

flutter:
  assets:
    - assets/icons/
  uses-material-design: true
