name: CI

on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.4'
          channel: "stable"
          cache: true
      - run: flutter config --no-analytics
      - run: ./patch/apply.sh
      - run: flutter build ios --profile --no-codesign
      - name: make ipa
        run: |
          mkdir Reactor
          cp -R ./build/ios/iphoneos/Runner.app ./Reactor
          zip -qq -r reactor.zip Reactor
          mv reactor.zip reactor.ipa
      - uses: actions/upload-artifact@v2
        with:
          name: reactor.ipa
          path: reactor.ipa
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.4'
          channel: "stable"
          cache: true
      - run: flutter config --no-analytics
      - run: ./patch/apply.sh
      - name: Decode and configure keystore
        env:
          ENCODED_KEY_STORE: ${{ secrets.KEY_STORE }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
        run: |
          ks_dir="$RUNNER_TEMP/keystore"
          ks_path="$ks_dir/reactor.jks"
          mkdir "$ks_dir"
          echo $ENCODED_KEY_STORE | base64 -di > $ks_path
          echo "storePassword=$KEY_STORE_PASSWORD" > ./android/key.properties
          echo "keyPassword=$KEY_PASSWORD" >> ./android/key.properties
          echo "keyAlias=$KEY_ALIAS" >> ./android/key.properties
          echo "storeFile=$ks_path" >> ./android/key.properties
      - run: flutter build apk --release
      - run: cp ./build/app/outputs/flutter-apk/app-release.apk ./reactor.apk
      - uses: actions/upload-artifact@v2
        with:
          name: reactor.apk
          path: reactor.apk
  git-release:
    runs-on: ubuntu-latest
    needs: [ build-android, build-ios ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: reactor.apk
      - uses: actions/download-artifact@v2
        with:
          name: reactor.ipa
      - name: Get the tag name
        run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "reactor.apk,reactor.ipa"
          name: Reactor ${{ env.TAG }}
          token: ${{ secrets.GITHUB_TOKEN }}
